theme: jekyll-theme-merlot
title: Welcome to Dustin's homepage!
description: Enjoy updates about current and upcoming projects.

This page will show differnt thing in the fiuture as I am about to dive deeper into GitHub and its possibiliries.
